#!/usr/local/bin/bash

if [ $# -lt 5 ] ; then
 echo "Usage: $0 brain1 brain2 skull1 skull2 outputmatrix [extra flirt args]"
 echo
 echo "  NB: brain2 and skull2 are used as -ref arguments internally"
 exit 1
fi

bin=$1; export bin
bref=$2; export bref
sin=$3; export sin
sref=$4; export sref
matf=$5; export matf
shift 5
args=$* ; export args

flirt=/usr/local/fsl/src/flirt/flirt ; export flirt

$flirt -in $bin -ref $bref -schedule ${FSLDIR}/bin/pairregrc1 -omat prgmat1 $args
$flirt -in $sin -ref $sref -init prgmat1 -schedule ${FSLDIR}/bin/pairregrc2 -omat prgmat2 $args
convert_xfm -matonly -fixscaleskew prgmat2 prgmat1 -omat prgmat3
$flirt -in $bin -ref $bref -init prgmat3 -schedule ${FSLDIR}/bin/pairregrc3 -omat $matf $args
