#!/bin/sh

if [ $# -lt 5 ] ; then
 echo "Usage: $0 brain1 brain2 skull1 skull2 outputmatrix [extra flirt args]"
 echo
 echo "  NB: brain1 and skull1 are used as -ref arguments internally"
 exit 1
fi

bref=$1; export bref
bin=$2; export bin
sref=$3; export sref
sin=$4; export sin
matf=$5; export matf
shift 5
args=$* ; export args

flirt=${FSLDIR}/bin/flirt ; export flirt

$flirt -in $bin -ref $bref -schedule ${FSLDIR}/bin/pairregrc1 -omat $matf.1.$$ $args
$flirt -in $sin -ref $sref -init $matf.1.$$ -schedule ${FSLDIR}/bin/pairregrc2 -omat $matf.2.$$ $args
${FSLDIR}/bin/convert_xfm -matonly -fixscaleskew $matf.2.$$ $matf.1.$$ -omat $matf.3.$$
$flirt -in $bin -ref $bref -init $matf.3.$$ -schedule ${FSLDIR}/bin/pairregrc3 -omat $matf $args
# tidy up the temporary matrices
rm -f $matf.1.$$ $matf.2.$$ $matf.3.$$