#!/bin/sh

function run { echo $1 ; $1 ; }

# prepare input images at required resolutions
if [ `imtest mjbrain8` = '0' ] ; then 
  run "flirt -in mjbrain -ref mjbrain -out mjbrain8 -applyisoxfm 8"
fi
if [ `imtest mjbrain4` = '0' ] ; then 
  run "flirt -in mjbrain -ref mjbrain -out mjbrain4 -applyisoxfm 4"
fi
if [ `imtest mjbrain2` = '0' ] ; then 
  run "flirt -in mjbrain -ref mjbrain -out mjbrain2 -applyisoxfm 2"
fi
if [ `imtest mjbrain1` = '0' ] ; then 
  run "flirt -in mjbrain -ref mjbrain -out mjbrain1 -applyisoxfm 1"
fi


# resample output for 4mm stage
if [ `imtest mjbrain4_to_colin4` = '0' ] ; then 
  run "flirt -in mjbrain4 -init mjbrain2colin.mat -ref colin4 -out mjbrain4_to_colin4 -applyxfm"
fi

# 4mm stages (with decreasing blurring/constraint)
run "./nonlin -i mjbrain4 -r colin4 -o grot4 -w grot4_warp --initaff=mjbrain2colin.mat -d -v --maxiter=6 --blursize=20"

run "./nonlin -i mjbrain4 -r colin4 -o grot4b -w postwarp4 -d -v --maxiter=4 --initwarp=grot4_warp --blursize=8"

# resample output warp for 2mm stage (include translational fixes? TODO)
run "flirt -in postwarp4 -ref colin2 -out prewarp2 -applyxfm"
if [ `imtest mjbrain2_to_colin2` = '0' ] ; then 
  run "flirt -in mjbrain2 -init mjbrain2colin.mat -ref colin2 -out mjbrain2_to_colin2 -applyxfm"
fi

# 2mm stages
run "./nonlin -i mjbrain2 -r colin2 -o grot2 -w grot2_warp -d -v --maxiter=4 --initwarp=prewarp2 --blursize=8"

run "./nonlin -i mjbrain2 -r colin2 -o grot2b -w postwarp2 -d -v --maxiter=4 --initwarp=grot2_warp --blursize=4"

# resample output warp for 2mm stage (include translational fixes? TODO)
run "flirt -in postwarp2 -ref colin1 -out prewarp1 -applyxfm"
if [ `imtest mjbrain1_to_colin1` = '0' ] ; then 
  run "flirt -in mjbrain1 -init mjbrain2colin.mat -ref colin1 -out mjbrain1_to_colin1 -applyxfm"
fi

# 1mm stages
run "./nonlin -i mjbrain1 -r colin1 -o grot1 -w grot1_warp -d -v --maxiter=4 --initwarp=prewarp1 --blursize=4"

# finished - display message for checking
echo " "
echo "Check results by running:"
echo fv colin1 mjbrain1_to_colin1 grot1

